#ifndef channel_STORAGE_H__
#define channel_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>


using namespace std;
using namespace boost;

/** Structure representing input of type channel.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class channel
{
public:

  /** Data type channel, default constructor */  
  typedef const boost::tuple<const int&>  identifier_type;

  channel() :
    chan_no(-901),
    length(-901),
    manning(-901.0),
    dispersion(-901.0),
    upnode(-901),
    downnode(-901),
    used(true),
    layer(0)
  {
    
  };

  /** Construct a channel with actual data values */
  channel(const int & a_chan_no,const int & a_length,const double & a_manning,const double & a_dispersion,const int & a_upnode,const int & a_downnode, bool a_used=true, int a_layer = 0) :
    chan_no(a_chan_no),
    length(a_length),
    manning(a_manning),
    dispersion(a_dispersion),
    upnode(a_upnode),
    downnode(a_downnode),
    used(a_used),
    layer(a_layer)
  {
      
  }
  
  /**Copy constructor) 
   */
  channel (const channel & other) :
    chan_no(other.chan_no),
    length(other.length),
    manning(other.manning),
    dispersion(other.dispersion),
    upnode(other.upnode),
    downnode(other.downnode),
    used(other.used),
    layer(other.layer)
  {
      
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( chan_no );
  }
  
  void set_identifier(identifier_type identifier)
  {
     chan_no=identifier.get<0>();
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  channel::identifier_type parent_identifier()  const
  {
     return channel::identifier_type( chan_no );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<channel>& pbuf = HDFTableManager<channel>::instance().buffer();
    channel parent;
    parent.set_identifier(parent_identifier());
    vector<channel>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<channel>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const channel & other) const
  {
     
     if(this->identifier() != other.identifier())
	 {
		 return this->identifier() < other.identifier();
	 }
	 // todo: make this a policy
	 bool layerOutranks = (this->layer == 0 && other.layer != 0) ||
		                  (this->layer > other.layer && other.layer != 0);
     return layerOutranks;

  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const channel & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  channel& operator=(const channel& rhs)
  {
    this->chan_no=rhs.chan_no;
    this->length=rhs.length;
    this->manning=rhs.manning;
    this->dispersion=rhs.dispersion;
    this->upnode=rhs.upnode;
    this->downnode=rhs.downnode;
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (channel) */
  string objectName() const
  { 
    return "channel"; 
  }

  
  int chan_no;
  int length;
  double manning;
  double dispersion;
  int upnode;
  int downnode;
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<channel> channel_table;

hid_t string_type(size_t n);

TableDescription channel_table_description();

istream& operator>> (istream& stream, channel & obj);
ostream& operator<<(ostream & stream, const channel & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void channel_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int channel_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void channel_append_to_buffer_f(const int * a_chan_no,const int * a_length,const double * a_manning,const double * a_dispersion,const int * a_upnode,const int * a_downnode, int * ierror);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void channel_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void channel_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void channel_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void channel_query_from_buffer_f(size_t* row, 
                        int * a_chan_no,int * a_length,double * a_manning,double * a_dispersion,int * a_upnode,int * a_downnode, int * ierror);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void channel_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void channel_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

