!> \defgroup fortran Application-Defined Data I/O FORTRAN API (autogenerated)
!! This is a listing of the automatically generated FORTRAN bindings
!! for reading and writing data from text and hdf5. Each routine is listed by
!! module_name::routine_name
!@{ 
module input_storage_fortran
	   contains

       // Fortran Include Files DO NOT ALTER THIS LINE AT ALL

       subroutine clear_all_buffers(ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_clear_all_buffers_f' :: clear_all_buffers_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'clear_all_buffers_f' :: clear_all_buffers_f
           !DEC$ END IF
         call clear_all_buffers_f(ierror)
       end subroutine
       
       subroutine prioritize_all_buffers(ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_prioritize_all_buffers_f' :: prioritize_all_buffers_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'prioritize_all_buffers_f' :: prioritize_all_buffers_f
           !DEC$ END IF
          integer :: ierror
          call prioritize_all_buffers_f(ierror)
       end subroutine

       subroutine write_all_buffers_to_text(textfile,append,ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_write_all_buffers_to_text_f' :: write_all_buffers_to_text_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'write_all_buffers_to_text_f' :: write_all_buffers_to_text_f
           !DEC$ END IF
         character*(*) textfile
         logical append
         integer :: ierror
         call write_all_buffers_to_text_f(textfile,append,ierror)
       end subroutine

       subroutine write_buffer_profile_to_text(profile,textfile,append,ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_write_buffer_profile_to_text_f' :: write_buffer_profile_to_text_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'write_buffer_profile_to_text_f' :: write_buffer_profile_to_text_f
           !DEC$ END IF
         character*(*) textfile,profile
         logical append
         integer :: ierror
         call write_buffer_profile_to_text_f(profile,textfile,append,ierror)
       end subroutine

       subroutine write_buffer_profile_to_hdf5(profile,file_id,ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_write_buffer_profile_to_hdf5_f' :: write_buffer_profile_to_hdf5_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'write_buffer_profile_to_hdf5_f' :: write_buffer_profile_to_hdf5_f
           !DEC$ END IF
         use hdf5, only: HID_T
         implicit none
         character*(*) :: profile         
         integer :: ierror         
         integer(HID_T), intent(in) :: file_id
         call write_buffer_profile_to_hdf5_f(profile,file_id,ierror)
       end subroutine       

       subroutine read_buffer_profile_from_hdf5(profile,file_id,ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_read_buffer_profile_from_hdf5_f' :: read_buffer_profile_from_hdf5_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'read_buffer_profile_from_hdf5_f' :: read_buffer_profile_from_hdf5_f
           !DEC$ END IF
         use hdf5, only: HID_T
         implicit none
         character*(*) :: profile         
         integer :: ierror         
         integer(HID_T), intent(in) :: file_id
         call read_buffer_profile_from_hdf5_f(profile,file_id,ierror)
       end subroutine       
       
       
       subroutine write_all_buffers_to_hdf5(file_id,ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_write_all_buffers_to_hdf5_f' :: write_all_buffers_to_hdf5_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'write_all_buffers_to_hdf5_f' :: write_all_buffers_to_hdf5_f
           !DEC$ END IF
         use hdf5, only: HID_T
         implicit none
         integer :: ierror         
         integer(HID_T), intent(in) :: file_id
         call write_all_buffers_to_hdf5_f(file_id,ierror)
       end subroutine
       
       subroutine init_file_reader(ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_init_file_reader_f' :: init_file_reader_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'init_file_reader_f' :: init_file_reader_f
           !DEC$ END IF
          integer :: ierror
          call init_file_reader_f(ierror)
       end subroutine       

       subroutine set_active_profile(profilename,ierror)
          character*(*) profilename
          integer :: ierror
            !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_set_active_profile_f' :: set_active_profile_f
            !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'set_active_profile_f' :: set_active_profile_f
            !DEC$ END IF
          call set_active_profile_f(trim(profilename),ierror)
       end subroutine 

       subroutine set_initial_context_profile(profilename)
           !DEC$ IF DEFINED(_WIN32)
            !DEC$ ATTRIBUTES ALIAS:'_set_initial_context_profile_f' :: set_initial_context_profile_f
           !DEC$ ELSE
            !DEC$ ATTRIBUTES ALIAS:'set_initial_context_profile_f' :: set_initial_context_profile_f
           !DEC$ END IF
            character*(*) profilename
            integer :: ierror
            call set_initial_context_profile_f(trim(profilename),ierror)
       end subroutine
       
       subroutine set_user_substitution_enabled(enabled,ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_set_user_substitution_enabled_f' :: set_user_substitution_enabled_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'set_user_substitution_enabled_f' :: set_user_substitution_enabled_f
           !DEC$ END IF
          logical enabled
          integer :: ierror
          call set_user_substitution_enabled_f(enabled,ierror)
       end subroutine   

       subroutine set_os_env_substitution_enabled(enabled,ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_set_os_env_substitution_enabled_f' :: set_os_env_substitution_enabled_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'set_os_env_substitution_enabled_f' :: set_os_env_substitution_enabled_f
           !DEC$ END IF
          logical enabled
          integer :: ierror
          call set_os_env_substitution_enabled_f(enabled,ierror)
       end subroutine         

       subroutine set_substitution_not_found_is_error(is_error,ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_set_substitution_not_found_is_error_f' :: set_substitution_not_found_is_error_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'set_substitution_not_found_is_error_f' :: set_substitution_not_found_is_error_f
           !DEC$ END IF
          logical is_error
          integer :: ierror
          call set_substitution_not_found_is_error_f(is_error,ierror)
       end subroutine
       
       subroutine process_text_substitution(ierror)
           !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_process_text_substitution_f' :: process_text_substitution_f
           !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'process_text_substitution_f' :: process_text_substitution_f
           !DEC$ END IF
          integer :: ierror
          call process_text_substitution_f(ierror)
       end subroutine        
 
        subroutine read_buffer_from_text(startfilename,ierror)
          character*(*) startfilename
          integer :: ierror
            !DEC$ IF DEFINED(_WIN32)
          !DEC$ ATTRIBUTES ALIAS:'_read_buffer_from_text_f' :: read_buffer_from_text_f
            !DEC$ ELSE
          !DEC$ ATTRIBUTES ALIAS:'read_buffer_from_text_f' :: read_buffer_from_text_f
            !DEC$ END IF
          call read_buffer_from_text_f(startfilename,ierror)
       end subroutine        

end module
!@}
