!> \defgroup fortran Application-Defined Data I/O FORTRAN API (autogenerated)
!! This is a listing of the automatically generated FORTRAN bindings
!! for reading and writing data from text and hdf5. Each routine is listed by
!! module_name::routine_name
!@{ 
module input_storage_fortran
	   contains

       // Fortran Include Files DO NOT ALTER THIS LINE AT ALL

       subroutine clear_all_buffers
          !DEC$ ATTRIBUTES ALIAS:'_clear_all_buffers_f' :: clear_all_buffers_f
         call clear_all_buffers_f()
       end subroutine
       subroutine prioritize_all_buffers()
          !DEC$ ATTRIBUTES ALIAS:'_prioritize_all_buffers_f' :: prioritize_all_buffers_f
         call prioritize_all_buffers_f
       end subroutine

       subroutine write_all_buffers_to_text(textfile,append)
          !DEC$ ATTRIBUTES ALIAS:'_write_all_buffers_to_text_f' :: write_all_buffers_to_text_f
         character*(*) textfile
         logical append
         call write_all_buffers_to_text_f(textfile,append)
       end subroutine

       subroutine write_all_buffers_to_hdf5(file_id)
          !DEC$ ATTRIBUTES ALIAS:'_write_all_buffers_to_hdf5_f' :: write_all_buffers_to_hdf5_f
         use hdf5, only: HID_T
         implicit none
         integer(HID_T), intent(in) :: file_id
         call write_all_buffers_to_hdf5_f(file_id)
       end subroutine
       
       subroutine init_file_reader()
          !DEC$ ATTRIBUTES ALIAS:'_init_file_reader_f' :: init_file_reader_f
          call init_file_reader_f
       end subroutine       

       subroutine set_active_profile(profilename)
          character*(*) profilename
          !DEC$ ATTRIBUTES ALIAS:'_set_active_profile_f' :: set_active_profile_f
          call set_active_profile_f(profilename)
       end subroutine 

       subroutine set_initial_context_profile(profilename)
          character*(*) profilename
          !DEC$ ATTRIBUTES ALIAS:'_set_initial_context_profile_f' :: set_initial_context_profile_f
          call set_initial_context_profile_f(profilename)
       end subroutine
       
       subroutine set_substitution_enabled(enabled)
          logical enabled
          !DEC$ ATTRIBUTES ALIAS:'_set_substitution_enabled_f' :: set_substitution_enabled_f
          call set_substitution_enabled_f(enabled)
       end subroutine   

       subroutine process_text_substitution()
          !DEC$ ATTRIBUTES ALIAS:'_process_text_substitution_f' :: process_text_substitution_f
          call process_text_substitution_f()
       end subroutine        
 
 
 
        subroutine read_buffer_from_text(startfilename)
          character*(*) startfilename
          !DEC$ ATTRIBUTES ALIAS:'_read_buffer_from_text_f' :: read_buffer_from_text_f
          call read_buffer_from_text_f(startfilename)
       end subroutine        

end module
!@}
