#ifndef qext_STORAGE_H__
#define qext_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>


using namespace std;
using namespace boost;

/** Structure representing input of type qext.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class qext
{
public:

  /** Data type qext, default constructor */  
  typedef const tuple<const std::string>  identifier_type;

  qext() :
    attached_obj_type(-901),
    attached_obj_no(-901),
    used(true),
    layer(0)
  {
    fill_n(name,32,'\0');
    fill_n(attach_obj_name,32,'\0');
  };

  /** Construct a qext with actual data values */
  qext(const  char a_name[32],const  char a_attach_obj_name[32],const int & a_attached_obj_type,const int & a_attached_obj_no, bool a_used=true, int a_layer = 0) :
    attached_obj_type(a_attached_obj_type),
    attached_obj_no(a_attached_obj_no),
    used(a_used),
    layer(a_layer)
  {
    memcpy(name,a_name,32);
    memcpy(attach_obj_name,a_attach_obj_name,32);  
  }
  
  /**Copy constructor) 
   */
  qext (const qext & other) :
    attached_obj_type(other.attached_obj_type),
    attached_obj_no(other.attached_obj_no),
    used(other.used),
    layer(other.layer)
  {
    memcpy(name,other.name,32);
    memcpy(attach_obj_name,other.attach_obj_name,32);  
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( name );
  }
  
  void set_identifier(identifier_type identifier)
  {
     memcpy(name,identifier.get<0>().c_str(),32);
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  qext::identifier_type parent_identifier()  const
  {
     return qext::identifier_type( name );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<qext>& pbuf = HDFTableManager<qext>::instance().buffer();
    qext parent;
    parent.set_identifier(parent_identifier());
    vector<qext>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<qext>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const qext & other) const
  {
     return (this->identifier() < other.identifier()) || (this->identifier() == other.identifier() && this->layer > other.layer);
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const qext & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  qext& operator=(const qext& rhs)
  {
    strcpy(this->name,rhs.name);
    strcpy(this->attach_obj_name,rhs.attach_obj_name);
    this->attached_obj_type=rhs.attached_obj_type;
    this->attached_obj_no=rhs.attached_obj_no;
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (qext) */
  string objectName() const
  { 
    return "qext"; 
  }

  
  char name[32];
  char attach_obj_name[32];
  int attached_obj_type;
  int attached_obj_no;
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<qext> qext_table;

hid_t string_type(size_t n);

TableDescription qext_table_description();

istream& operator>> (istream& stream, qext & obj);
ostream& operator<<(ostream & stream, const qext & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void qext_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int qext_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void qext_append_to_buffer_f(const  char a_name[32],const  char a_attach_obj_name[32],const int * a_attached_obj_type,const int * a_attached_obj_no, int * ierror, 
              const int name_len,const int attach_obj_name_len);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void qext_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void qext_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void qext_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void qext_query_from_buffer_f(size_t* row, 
                         char a_name[32], char a_attach_obj_name[32],int * a_attached_obj_type,int * a_attached_obj_no, int * ierror, 
              int name_len,int attach_obj_name_len);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void qext_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void qext_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

