site_name: DSM2 version 8.2
repo_url: https://github.com/CADWRDeltaModeling/dsm2
edit_uri: edit/mkdocs/docs/
nav:
 - Home: index.md
 - Getting Started: getting_started.md
 - Manual: manual/index.md
 - Reference: reference/Background_Material_and_References.md
 - Installation: installation.md
 - Quick Start: quick_start.md
 - Tutorials: tutorials/Tutorials.md
 - FAQs: faqs/index.md
 - Release Notes: releasenotes.md
#theme: readthedocs
theme:
 name: material

