/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DWR_DMS_PTM_PTMFixedData */

#ifndef _Included_DWR_DMS_PTM_PTMFixedData
#define _Included_DWR_DMS_PTM_PTMFixedData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DWR_DMS_PTM_PTMFixedData_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfWaterbodies
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfWaterbodies
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfChannels
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfChannelGroups
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfChannelGroups
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfReservoirs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfReservoirs
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfDiversions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfDiversions
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfPumps
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfPumps
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfBoundaryWaterbodies
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfBoundaryWaterbodies
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfConveyors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfConveyors
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfNodes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfNodes
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfXSections
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfXSections
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfWaterbodies
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfWaterbodies
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfChannels
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfReservoirs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfReservoirs
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfDiversions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfDiversions
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfPumps
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfPumps
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfBoundaryWaterbodies
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfBoundaryWaterbodies
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfStageBoundaries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfStageBoundaries
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfConveyors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfConveyors
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfNodes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfNodes
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfXSections
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfXSections
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getMaximumNumberOfReservoirNodes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getMaximumNumberOfReservoirNodes
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getUniqueIdForChannel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getUniqueIdForChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getUniqueIdForReservoir
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getUniqueIdForReservoir
  (JNIEnv *, jclass, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getUniqueIdForBoundary
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getUniqueIdForBoundary
  (JNIEnv *, jclass, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getUniqueIdForStageBoundary
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getUniqueIdForStageBoundary
  (JNIEnv *, jclass, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getUniqueIdForConveyor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getUniqueIdForConveyor
  (JNIEnv *, jclass, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    doesQualBinaryExist
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_doesQualBinaryExist
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getQualConstituentNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getQualConstituentNames
  (JNIEnv *, jclass);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getWaterBodyName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DWR_DMS_PTM_PTMFixedData_getWaterBodyName
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfWaterbodiesForNode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfWaterbodiesForNode
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getWaterbodyIdArrayForNode
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getWaterbodyIdArrayForNode
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getWaterbodyObjectType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getWaterbodyObjectType
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getWaterbodyType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getWaterbodyType
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getWaterbodyGroup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getWaterbodyGroup
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getLocalIdForWaterbody
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getLocalIdForWaterbody
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNodeArrayForWaterbody
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNodeArrayForWaterbody
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getBoundaryTypeForNode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DWR_DMS_PTM_PTMFixedData_getBoundaryTypeForNode
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getChannelLength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getChannelLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getChannelNodeArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getChannelNodeArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getChannelXSectionIds
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getChannelXSectionIds
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getChannelXSectionDistances
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getChannelXSectionDistances
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getReservoirArea
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_DWR_DMS_PTM_PTMFixedData_getReservoirArea
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getReservoirBottomElevation
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_DWR_DMS_PTM_PTMFixedData_getReservoirBottomElevation
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getReservoirName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DWR_DMS_PTM_PTMFixedData_getReservoirName
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getReservoirNodeArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getReservoirNodeArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getDiversionNodeArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getDiversionNodeArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getPumpNodeArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getPumpNodeArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getBoundaryWaterbodyNodeArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getBoundaryWaterbodyNodeArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getConveyorNodeArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getConveyorNodeArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getConveyorName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DWR_DMS_PTM_PTMFixedData_getConveyorName
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getXSectionWidths
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getXSectionWidths
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getXSectionElevations
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getXSectionElevations
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getXSectionAreas
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getXSectionAreas
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getXSectionMinimumElevation
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_DWR_DMS_PTM_PTMFixedData_getXSectionMinimumElevation
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getParticleBooleanInputs
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getParticleBooleanInputs
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getParticleFloatInputs
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getParticleFloatInputs
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getParticleNumberOfInjections
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getParticleNumberOfInjections
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getParticleInjectionNodes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getParticleInjectionNodes
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getParticleNumberOfParticlesInjected
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getParticleNumberOfParticlesInjected
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getParticleInjectionStartJulmin
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getParticleInjectionStartJulmin
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getParticleInjectionLengthJulmin
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getParticleInjectionLengthJulmin
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfFluxes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfFluxes
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getFluxIncoming
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getFluxIncoming
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getFluxOutgoing
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getFluxOutgoing
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getFluxIncomingType
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getFluxIncomingType
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getFluxOutgoingType
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getFluxOutgoingType
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getNumberOfGroupOutputs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getNumberOfGroupOutputs
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getGroupMemberType
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getGroupMemberType
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getGroupMemberIndex
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_DWR_DMS_PTM_PTMFixedData_getGroupMemberIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getModelStartTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getModelStartTime
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getModelEndTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getModelEndTime
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getPTMTimeStep
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getPTMTimeStep
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getDisplayInterval
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getDisplayInterval
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getAnimationFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DWR_DMS_PTM_PTMFixedData_getAnimationFileName
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getAnimationOutputInterval
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getAnimationOutputInterval
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getBehaviorFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DWR_DMS_PTM_PTMFixedData_getBehaviorFileName
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getBehaviorInfileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DWR_DMS_PTM_PTMFixedData_getBehaviorInfileName
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getTraceFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DWR_DMS_PTM_PTMFixedData_getTraceFileName
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getTraceOutputInterval
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getTraceOutputInterval
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getRestartOutputFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DWR_DMS_PTM_PTMFixedData_getRestartOutputFileName
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getRestartOutputInterval
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DWR_DMS_PTM_PTMFixedData_getRestartOutputInterval
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFixedData
 * Method:    getRestartInputFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DWR_DMS_PTM_PTMFixedData_getRestartInputFileName
  (JNIEnv *, jobject);
 
#ifdef __cplusplus
}
#endif
#endif
