#ifndef transfer_STORAGE_H__
#define transfer_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>


using namespace std;
using namespace boost;

/** Structure representing input of type transfer.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class transfer
{
public:

  /** Data type transfer, default constructor */  
  typedef const boost::tuple<const std::string>  identifier_type;

  transfer() :
    
    used(true),
    layer(0)
  {
    fill_n(name,32,'\0');
    fill_n(from_obj,16,'\0');
    fill_n(from_identifier,32,'\0');
    fill_n(to_obj,16,'\0');
    fill_n(to_identifier,32,'\0');
  };

  /** Construct a transfer with actual data values */
  transfer(const  char a_name[32],const  char a_from_obj[16],const  char a_from_identifier[32],const  char a_to_obj[16],const  char a_to_identifier[32], bool a_used=true, int a_layer = 0) :
    
    used(a_used),
    layer(a_layer)
  {
    memcpy(name,a_name,32);
    memcpy(from_obj,a_from_obj,16);
    memcpy(from_identifier,a_from_identifier,32);
    memcpy(to_obj,a_to_obj,16);
    memcpy(to_identifier,a_to_identifier,32);  
  }
  
  /**Copy constructor) 
   */
  transfer (const transfer & other) :
    
    used(other.used),
    layer(other.layer)
  {
    memcpy(name,other.name,32);
    memcpy(from_obj,other.from_obj,16);
    memcpy(from_identifier,other.from_identifier,32);
    memcpy(to_obj,other.to_obj,16);
    memcpy(to_identifier,other.to_identifier,32);  
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( name );
  }
  
  void set_identifier(identifier_type identifier)
  {
     memcpy(name,identifier.get<0>().c_str(),32);
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  transfer::identifier_type parent_identifier()  const
  {
     return transfer::identifier_type( name );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<transfer>& pbuf = HDFTableManager<transfer>::instance().buffer();
    transfer parent;
    parent.set_identifier(parent_identifier());
    vector<transfer>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<transfer>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const transfer & other) const
  {
     
     if(this->identifier() != other.identifier())
	 {
		 return this->identifier() < other.identifier();
	 }
	 // todo: make this a policy
	 bool layerOutranks = (this->layer == 0 && other.layer != 0) ||
		                  (this->layer > other.layer && other.layer != 0);
     return layerOutranks;

  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const transfer & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  transfer& operator=(const transfer& rhs)
  {
    strcpy(this->name,rhs.name);
    strcpy(this->from_obj,rhs.from_obj);
    strcpy(this->from_identifier,rhs.from_identifier);
    strcpy(this->to_obj,rhs.to_obj);
    strcpy(this->to_identifier,rhs.to_identifier);
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (transfer) */
  string objectName() const
  { 
    return "transfer"; 
  }

  
  char name[32];
  char from_obj[16];
  char from_identifier[32];
  char to_obj[16];
  char to_identifier[32];
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<transfer> transfer_table;

hid_t string_type(size_t n);

TableDescription transfer_table_description();

istream& operator>> (istream& stream, transfer & obj);
ostream& operator<<(ostream & stream, const transfer & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void transfer_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int transfer_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void transfer_append_to_buffer_f(const  char a_name[32],const  char a_from_obj[16],const  char a_from_identifier[32],const  char a_to_obj[16],const  char a_to_identifier[32], int * ierror, 
              const int name_len,const int from_obj_len,const int from_identifier_len,const int to_obj_len,const int to_identifier_len);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void transfer_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void transfer_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void transfer_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void transfer_query_from_buffer_f(size_t* row, 
                         char a_name[32], char a_from_obj[16], char a_from_identifier[32], char a_to_obj[16], char a_to_identifier[32], int * ierror, 
              int name_len,int from_obj_len,int from_identifier_len,int to_obj_len,int to_identifier_len);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void transfer_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void transfer_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

