#ifndef xsect_STORAGE_H__
#define xsect_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>
#include "input_storage_channel.h"

using namespace std;
using namespace boost;

/** Structure representing input of type xsect.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class xsect
{
public:

  /** Data type xsect, default constructor */  
  typedef const boost::tuple<const int&,const double&>  identifier_type;

  xsect() :
    chan_no(-901),
    dist(-901.0),
    used(true),
    layer(0)
  {
    fill_n(file,128,'\0');
  };

  /** Construct a xsect with actual data values */
  xsect(const int & a_chan_no,const double & a_dist,const  char a_file[128], bool a_used=true, int a_layer = 0) :
    chan_no(a_chan_no),
    dist(a_dist),
    used(a_used),
    layer(a_layer)
  {
    memcpy(file,a_file,128);  
  }
  
  /**Copy constructor) 
   */
  xsect (const xsect & other) :
    chan_no(other.chan_no),
    dist(other.dist),
    used(other.used),
    layer(other.layer)
  {
    memcpy(file,other.file,128);  
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( chan_no,dist );
  }
  
  void set_identifier(identifier_type identifier)
  {
     chan_no=identifier.get<0>();
      dist=identifier.get<1>();
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  channel::identifier_type parent_identifier()  const
  {
     return channel::identifier_type( chan_no );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<channel>& pbuf = HDFTableManager<channel>::instance().buffer();
    channel parent;
    parent.set_identifier(parent_identifier());
    vector<channel>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<channel>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const xsect & other) const
  {
      return (this->identifier() < other.identifier());
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const xsect & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  xsect& operator=(const xsect& rhs)
  {
    this->chan_no=rhs.chan_no;
    this->dist=rhs.dist;
    strcpy(this->file,rhs.file);
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (xsect) */
  string objectName() const
  { 
    return "xsect"; 
  }

  
  int chan_no;
  double dist;
  char file[128];
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<xsect> xsect_table;

hid_t string_type(size_t n);

TableDescription xsect_table_description();

istream& operator>> (istream& stream, xsect & obj);
ostream& operator<<(ostream & stream, const xsect & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void xsect_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int xsect_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void xsect_append_to_buffer_f(const int * a_chan_no,const double * a_dist,const  char a_file[128], int * ierror, 
              const int file_len);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void xsect_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void xsect_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void xsect_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void xsect_query_from_buffer_f(size_t* row, 
                        int * a_chan_no,double * a_dist, char a_file[128], int * ierror, 
              int file_len);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void xsect_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void xsect_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

