#ifndef group_variable_sed_STORAGE_H__
#define group_variable_sed_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>


using namespace std;
using namespace boost;

/** Structure representing input of type group_variable_sed.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class group_variable_sed
{
public:

  /** Data type group_variable_sed, default constructor */  
  typedef const boost::tuple<const std::string,const int&,const int&,const std::string>  identifier_type;

  group_variable_sed() :
    sed_zone(-901),
    sed_layer(-901),
    value(-901.0),
    used(true),
    layer(0)
  {
    fill_n(group_name,32,'\0');
    fill_n(variable,16,'\0');
  };

  /** Construct a group_variable_sed with actual data values */
  group_variable_sed(const  char a_group_name[32],const int & a_sed_zone,const int & a_sed_layer,const  char a_variable[16],const double & a_value, bool a_used=true, int a_layer = 0) :
    sed_zone(a_sed_zone),
    sed_layer(a_sed_layer),
    value(a_value),
    used(a_used),
    layer(a_layer)
  {
    memcpy(group_name,a_group_name,32);
    memcpy(variable,a_variable,16);  
  }
  
  /**Copy constructor) 
   */
  group_variable_sed (const group_variable_sed & other) :
    sed_zone(other.sed_zone),
    sed_layer(other.sed_layer),
    value(other.value),
    used(other.used),
    layer(other.layer)
  {
    memcpy(group_name,other.group_name,32);
    memcpy(variable,other.variable,16);  
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( group_name,sed_zone,sed_layer,variable );
  }
  
  void set_identifier(identifier_type identifier)
  {
     memcpy(group_name,identifier.get<0>().c_str(),32);
      sed_zone=identifier.get<1>();
      sed_layer=identifier.get<2>();
      memcpy(variable,identifier.get<3>().c_str(),16);
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  group_variable_sed::identifier_type parent_identifier()  const
  {
     return group_variable_sed::identifier_type( group_name,sed_zone,sed_layer,variable );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<group_variable_sed>& pbuf = HDFTableManager<group_variable_sed>::instance().buffer();
    group_variable_sed parent;
    parent.set_identifier(parent_identifier());
    vector<group_variable_sed>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<group_variable_sed>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const group_variable_sed & other) const
  {
     
     if(this->identifier() != other.identifier())
	 {
		 return this->identifier() < other.identifier();
	 }
	 // todo: make this a policy
	 bool layerOutranks = (this->layer == 0 && other.layer != 0) ||
		                  (this->layer > other.layer && other.layer != 0);
     return layerOutranks;

  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const group_variable_sed & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  group_variable_sed& operator=(const group_variable_sed& rhs)
  {
    strcpy(this->group_name,rhs.group_name);
    this->sed_zone=rhs.sed_zone;
    this->sed_layer=rhs.sed_layer;
    strcpy(this->variable,rhs.variable);
    this->value=rhs.value;
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (group_variable_sed) */
  string objectName() const
  { 
    return "group_variable_sed"; 
  }

  
  char group_name[32];
  int sed_zone;
  int sed_layer;
  char variable[16];
  double value;
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<group_variable_sed> group_variable_sed_table;

hid_t string_type(size_t n);

TableDescription group_variable_sed_table_description();

istream& operator>> (istream& stream, group_variable_sed & obj);
ostream& operator<<(ostream & stream, const group_variable_sed & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void group_variable_sed_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int group_variable_sed_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void group_variable_sed_append_to_buffer_f(const  char a_group_name[32],const int * a_sed_zone,const int * a_sed_layer,const  char a_variable[16],const double * a_value, int * ierror, 
              const int group_name_len,const int variable_len);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void group_variable_sed_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void group_variable_sed_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void group_variable_sed_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void group_variable_sed_query_from_buffer_f(size_t* row, 
                         char a_group_name[32],int * a_sed_zone,int * a_sed_layer, char a_variable[16],double * a_value, int * ierror, 
              int group_name_len,int variable_len);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void group_variable_sed_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void group_variable_sed_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

