#ifndef xsect_layer_STORAGE_H__
#define xsect_layer_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>
#include "input_storage_channel.h"

using namespace std;
using namespace boost;

/** Structure representing input of type xsect_layer.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class xsect_layer
{
public:

  /** Data type xsect_layer, default constructor */  
  typedef const boost::tuple<const int&,const double&,const double&>  identifier_type;

  xsect_layer() :
    chan_no(-901),
    dist(-901.0),
    elev(-901.0),
    area(-901.0),
    width(-901.0),
    wet_perim(-901.0),
    used(true),
    layer(0)
  {
    
  };

  /** Construct a xsect_layer with actual data values */
  xsect_layer(const int & a_chan_no,const double & a_dist,const double & a_elev,const double & a_area,const double & a_width,const double & a_wet_perim, bool a_used=true, int a_layer = 0) :
    chan_no(a_chan_no),
    dist(a_dist),
    elev(a_elev),
    area(a_area),
    width(a_width),
    wet_perim(a_wet_perim),
    used(a_used),
    layer(a_layer)
  {
      
  }
  
  /**Copy constructor) 
   */
  xsect_layer (const xsect_layer & other) :
    chan_no(other.chan_no),
    dist(other.dist),
    elev(other.elev),
    area(other.area),
    width(other.width),
    wet_perim(other.wet_perim),
    used(other.used),
    layer(other.layer)
  {
      
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( chan_no,dist,elev );
  }
  
  void set_identifier(identifier_type identifier)
  {
     chan_no=identifier.get<0>();
      dist=identifier.get<1>();
      elev=identifier.get<2>();
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  channel::identifier_type parent_identifier()  const
  {
     return channel::identifier_type( chan_no );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<channel>& pbuf = HDFTableManager<channel>::instance().buffer();
    channel parent;
    parent.set_identifier(parent_identifier());
    vector<channel>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<channel>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const xsect_layer & other) const
  {
      return (this->identifier() < other.identifier());
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const xsect_layer & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  xsect_layer& operator=(const xsect_layer& rhs)
  {
    this->chan_no=rhs.chan_no;
    this->dist=rhs.dist;
    this->elev=rhs.elev;
    this->area=rhs.area;
    this->width=rhs.width;
    this->wet_perim=rhs.wet_perim;
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (xsect_layer) */
  string objectName() const
  { 
    return "xsect_layer"; 
  }

  
  int chan_no;
  double dist;
  double elev;
  double area;
  double width;
  double wet_perim;
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<xsect_layer> xsect_layer_table;

hid_t string_type(size_t n);

TableDescription xsect_layer_table_description();

istream& operator>> (istream& stream, xsect_layer & obj);
ostream& operator<<(ostream & stream, const xsect_layer & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void xsect_layer_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int xsect_layer_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void xsect_layer_append_to_buffer_f(const int * a_chan_no,const double * a_dist,const double * a_elev,const double * a_area,const double * a_width,const double * a_wet_perim, int * ierror);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void xsect_layer_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void xsect_layer_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void xsect_layer_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void xsect_layer_query_from_buffer_f(size_t* row, 
                        int * a_chan_no,double * a_dist,double * a_elev,double * a_area,double * a_width,double * a_wet_perim, int * ierror);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void xsect_layer_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void xsect_layer_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

