/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DWR_DMS_PTM_PTMFluxOutput */

#ifndef _Included_DWR_DMS_PTM_PTMFluxOutput
#define _Included_DWR_DMS_PTM_PTMFluxOutput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DWR_DMS_PTM_PTMFluxOutput
 * Method:    initializeFluxOutput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DWR_DMS_PTM_PTMFluxOutput_initializeFluxOutput
  (JNIEnv *, jobject, jint);

/*
 * Class:     DWR_DMS_PTM_PTMFluxOutput
 * Method:    writeFluxOutput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DWR_DMS_PTM_PTMFluxOutput_writeFluxOutput
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFluxOutput
 * Method:    closeFluxOutput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DWR_DMS_PTM_PTMFluxOutput_closeFluxOutput
  (JNIEnv *, jobject);

/*
 * Class:     DWR_DMS_PTM_PTMFluxOutput
 * Method:    setFlux
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_DWR_DMS_PTM_PTMFluxOutput_setFlux
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     DWR_DMS_PTM_PTMFluxOutput
 * Method:    setGroup
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_DWR_DMS_PTM_PTMFluxOutput_setGroup
  (JNIEnv *, jobject, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
