!> \defgroup fortran Application-Defined Data I/O FORTRAN API (autogenerated)
!! This is a listing of the automatically generated FORTRAN bindings
!! for reading and writing data from text and hdf5. Each routine is listed by
!! module_name::routine_name
!@{
module dsm2_tidefile_input_storage_fortran
contains
       include "qext_input_storage.fi"
       include "hydro_comp_point_input_storage.fi"
       include "reservoir_flow_connections_input_storage.fi"
       include "node_flow_connections_input_storage.fi"
       include "reservoir_node_connect_input_storage.fi"
       include "stage_boundaries_input_storage.fi"
       include "virtual_xsect_input_storage.fi"
end module
!@}
