#ifndef virtual_xsect_STORAGE_H__
#define virtual_xsect_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE
DO NOT CHANGE THE CODE HERE.
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>


using namespace std;
using namespace boost;

/** Structure representing input of type virtual_xsect.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class virtual_xsect
{
public:

  /** Data type virtual_xsect, default constructor */
  typedef const boost::tuple<const int&>  identifier_type;

  virtual_xsect() :
    chan_no(-901),
    num_virt_sec(-901),
    vsecno(-901),
    num_elev(-901),
    min_elev(-901.0),
    elevation(-901.0),
    area(-901.0),
    wet_p(-901.0),
    width(-901.0),
    used(true),
    layer(0)
  {

  };

  /** Construct a virtual_xsect with actual data values */
  virtual_xsect(const int & a_chan_no,const int & a_num_virt_sec,const int & a_vsecno,const int & a_num_elev,const double & a_min_elev,const double & a_elevation,const double & a_area,const double & a_wet_p,const double & a_width, bool a_used=true, int a_layer = 0) :
    chan_no(a_chan_no),
    num_virt_sec(a_num_virt_sec),
    vsecno(a_vsecno),
    num_elev(a_num_elev),
    min_elev(a_min_elev),
    elevation(a_elevation),
    area(a_area),
    wet_p(a_wet_p),
    width(a_width),
    used(a_used),
    layer(a_layer)
  {

  }

  /**Copy constructor)
   */
  virtual_xsect (const virtual_xsect & other) :
    chan_no(other.chan_no),
    num_virt_sec(other.num_virt_sec),
    vsecno(other.vsecno),
    num_elev(other.num_elev),
    min_elev(other.min_elev),
    elevation(other.elevation),
    area(other.area),
    wet_p(other.wet_p),
    width(other.width),
    used(other.used),
    layer(other.layer)
  {

  }

  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {
     return identifier_type( chan_no );
  }

  void set_identifier(identifier_type identifier)
  {
     chan_no=identifier.get<0>();
  }

  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  virtual_xsect::identifier_type parent_identifier()  const
  {
     return virtual_xsect::identifier_type( chan_no );
  }

  /** Return the version/layer number of the parent object */
  int parent_version()  const
  {
    vector<virtual_xsect>& pbuf = HDFTableManager<virtual_xsect>::instance().buffer();
    virtual_xsect parent;
    parent.set_identifier(parent_identifier());
    vector<virtual_xsect>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<virtual_xsect>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/
  bool operator< (const virtual_xsect & other) const
  {

     if(this->identifier() != other.identifier())
	 {
		 return this->identifier() < other.identifier();
	 }
	 // todo: make this a policy
	 bool layerOutranks = (this->layer == 0 && other.layer != 0) ||
		                  (this->layer > other.layer && other.layer != 0);
     return layerOutranks;

  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/
  bool operator== (const virtual_xsect & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }

  /** Assignment that includes all the data plus the used and layer fields */
  virtual_xsect& operator=(const virtual_xsect& rhs)
  {
    this->chan_no=rhs.chan_no;
    this->num_virt_sec=rhs.num_virt_sec;
    this->vsecno=rhs.vsecno;
    this->num_elev=rhs.num_elev;
    this->min_elev=rhs.min_elev;
    this->elevation=rhs.elevation;
    this->area=rhs.area;
    this->wet_p=rhs.wet_p;
    this->width=rhs.width;
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (virtual_xsect) */
  string objectName() const
  {
    return "virtual_xsect";
  }


  int chan_no;
  int num_virt_sec;
  int vsecno;
  int num_elev;
  double min_elev;
  double elevation;
  double area;
  double wet_p;
  double width;
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<virtual_xsect> virtual_xsect_table;

hid_t string_type(size_t n);

TableDescription virtual_xsect_table_description();

istream& operator>> (istream& stream, virtual_xsect & obj);
ostream& operator<<(ostream & stream, const virtual_xsect & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/
FCALL void virtual_xsect_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int virtual_xsect_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void virtual_xsect_append_to_buffer_f(const int * a_chan_no,const int * a_num_virt_sec,const int * a_vsecno,const int * a_num_elev,const double * a_min_elev,const double * a_elevation,const double * a_area,const double * a_wet_p,const double * a_width, int * ierror);

/** both makes the table and writes the contents of the buffer to it */
FCALL void virtual_xsect_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void virtual_xsect_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void virtual_xsect_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void virtual_xsect_query_from_buffer_f(int32_t* row,
                        int * a_chan_no,int * a_num_virt_sec,int * a_vsecno,int * a_num_elev,double * a_min_elev,double * a_elevation,double * a_area,double * a_wet_p,double * a_width, int * ierror);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void virtual_xsect_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void virtual_xsect_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

