#ifndef hydro_comp_point_STORAGE_H__
#define hydro_comp_point_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>


using namespace std;
using namespace boost;

/** Structure representing input of type hydro_comp_point.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class hydro_comp_point
{
public:

  /** Data type hydro_comp_point, default constructor */  
  typedef const boost::tuple<const int&>  identifier_type;

  hydro_comp_point() :
    comp_index(-901),
    channel(-901),
    distance(-901.0),
    used(true),
    layer(0)
  {
    
  };

  /** Construct a hydro_comp_point with actual data values */
  hydro_comp_point(const int & a_comp_index,const int & a_channel,const double & a_distance, bool a_used=true, int a_layer = 0) :
    comp_index(a_comp_index),
    channel(a_channel),
    distance(a_distance),
    used(a_used),
    layer(a_layer)
  {
      
  }
  
  /**Copy constructor) 
   */
  hydro_comp_point (const hydro_comp_point & other) :
    comp_index(other.comp_index),
    channel(other.channel),
    distance(other.distance),
    used(other.used),
    layer(other.layer)
  {
      
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( comp_index );
  }
  
  void set_identifier(identifier_type identifier)
  {
     comp_index=identifier.get<0>();
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  hydro_comp_point::identifier_type parent_identifier()  const
  {
     return hydro_comp_point::identifier_type( comp_index );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<hydro_comp_point>& pbuf = HDFTableManager<hydro_comp_point>::instance().buffer();
    hydro_comp_point parent;
    parent.set_identifier(parent_identifier());
    vector<hydro_comp_point>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<hydro_comp_point>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const hydro_comp_point & other) const
  {
     
     if(this->identifier() != other.identifier())
	 {
		 return this->identifier() < other.identifier();
	 }
	 // todo: make this a policy
	 bool layerOutranks = (this->layer == 0 && other.layer != 0) ||
		                  (this->layer > other.layer && other.layer != 0);
     return layerOutranks;

  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const hydro_comp_point & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  hydro_comp_point& operator=(const hydro_comp_point& rhs)
  {
    this->comp_index=rhs.comp_index;
    this->channel=rhs.channel;
    this->distance=rhs.distance;
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (hydro_comp_point) */
  string objectName() const
  { 
    return "hydro_comp_point"; 
  }

  
  int comp_index;
  int channel;
  double distance;
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<hydro_comp_point> hydro_comp_point_table;

hid_t string_type(size_t n);

TableDescription hydro_comp_point_table_description();

istream& operator>> (istream& stream, hydro_comp_point & obj);
ostream& operator<<(ostream & stream, const hydro_comp_point & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void hydro_comp_point_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int hydro_comp_point_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void hydro_comp_point_append_to_buffer_f(const int * a_comp_index,const int * a_channel,const double * a_distance, int * ierror);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void hydro_comp_point_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void hydro_comp_point_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void hydro_comp_point_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void hydro_comp_point_query_from_buffer_f(int32_t* row, 
                        int * a_comp_index,int * a_channel,double * a_distance, int * ierror);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void hydro_comp_point_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void hydro_comp_point_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

