c-----DSS interval information
      integer*4
     &     jmin_15min           ! julian minute of end-of-period for 15MIN data
     &     ,jmin_1hour
     &     ,jmin_1day
     &     ,jmin_1week
     &     ,jmin_1month
     &     ,jmin_1year
     &     ,jmin_15min_prev     ! previous value of jmin_15min
     &     ,jmin_1hour_prev
     &     ,jmin_1day_prev
     &     ,jmin_1week_prev
     &     ,jmin_1month_prev
     &     ,jmin_1year_prev

      common /dss_intvl_i/
     &     jmin_15min           ! julian minute of end-of-period for 15MIN data
     &     ,jmin_1hour
     &     ,jmin_1day
     &     ,jmin_1week
     &     ,jmin_1month
     &     ,jmin_1year
     &     ,jmin_15min_prev     ! previous value of jmin_15min
     &     ,jmin_1hour_prev
     &     ,jmin_1day_prev
     &     ,jmin_1week_prev
     &     ,jmin_1month_prev
     &     ,jmin_1year_prev