#!/bin/bash
# This script assumes that a DSM2 package with a bin folder is available in this directory
# Copy the DSM2 package generated by Jenkins to this directory before running these commands
docker build --target dsm2-base -t dsm2-base .
docker build --target dsm2-aws -t dsm2-aws .
