!> \defgroup fortran Application-Defined Data I/O FORTRAN API (autogenerated)
!! This is a listing of the automatically generated FORTRAN bindings
!! for reading and writing data from text and hdf5. Each routine is listed by
!! module_name::routine_name
!@{ 
module input_storage_fortran_data
       contains

       // Fortran Include Files DO NOT ALTER THIS LINE AT ALL

       subroutine clear_all_buffers
         call clear_all_buffers_f()
       end subroutine
       subroutine prioritize_all_buffers()
         call prioritize_all_buffers_f
       end subroutine
end module
!@}
