
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer op_rule_create_buffer
#define yy_delete_buffer op_rule_delete_buffer
#define yy_scan_buffer op_rule_scan_buffer
#define yy_scan_string op_rule_scan_string
#define yy_scan_bytes op_rule_scan_bytes
#define yy_init_buffer op_rule_init_buffer
#define yy_flush_buffer op_rule_flush_buffer
#define yy_load_buffer_state op_rule_load_buffer_state
#define yy_switch_to_buffer op_rule_switch_to_buffer
#define yypush_buffer_state op_rulepush_buffer_state
#define yypop_buffer_state op_rulepop_buffer_state
#define yyensure_buffer_stack op_ruleensure_buffer_stack
#define yy_flex_debug op_rule_flex_debug
#define yyin op_rulein
#define yyleng op_ruleleng
#define yylex op_rulelex
#define yylineno op_rulelineno
#define yyout op_ruleout
#define yyrestart op_rulerestart
#define yytext op_ruletext
#define yywrap op_rulewrap
#define yyalloc op_rulealloc
#define yyrealloc op_rulerealloc
#define yyfree op_rulefree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define op_rule_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer op_rule_create_buffer
#endif

#ifdef yy_delete_buffer
#define op_rule_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer op_rule_delete_buffer
#endif

#ifdef yy_scan_buffer
#define op_rule_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer op_rule_scan_buffer
#endif

#ifdef yy_scan_string
#define op_rule_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string op_rule_scan_string
#endif

#ifdef yy_scan_bytes
#define op_rule_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes op_rule_scan_bytes
#endif

#ifdef yy_init_buffer
#define op_rule_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer op_rule_init_buffer
#endif

#ifdef yy_flush_buffer
#define op_rule_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer op_rule_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define op_rule_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state op_rule_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define op_rule_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer op_rule_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define op_rulepush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state op_rulepush_buffer_state
#endif

#ifdef yypop_buffer_state
#define op_rulepop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state op_rulepop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define op_ruleensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack op_ruleensure_buffer_stack
#endif

#ifdef yylex
#define op_rulelex_ALREADY_DEFINED
#else
#define yylex op_rulelex
#endif

#ifdef yyrestart
#define op_rulerestart_ALREADY_DEFINED
#else
#define yyrestart op_rulerestart
#endif

#ifdef yylex_init
#define op_rulelex_init_ALREADY_DEFINED
#else
#define yylex_init op_rulelex_init
#endif

#ifdef yylex_init_extra
#define op_rulelex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra op_rulelex_init_extra
#endif

#ifdef yylex_destroy
#define op_rulelex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy op_rulelex_destroy
#endif

#ifdef yyget_debug
#define op_ruleget_debug_ALREADY_DEFINED
#else
#define yyget_debug op_ruleget_debug
#endif

#ifdef yyset_debug
#define op_ruleset_debug_ALREADY_DEFINED
#else
#define yyset_debug op_ruleset_debug
#endif

#ifdef yyget_extra
#define op_ruleget_extra_ALREADY_DEFINED
#else
#define yyget_extra op_ruleget_extra
#endif

#ifdef yyset_extra
#define op_ruleset_extra_ALREADY_DEFINED
#else
#define yyset_extra op_ruleset_extra
#endif

#ifdef yyget_in
#define op_ruleget_in_ALREADY_DEFINED
#else
#define yyget_in op_ruleget_in
#endif

#ifdef yyset_in
#define op_ruleset_in_ALREADY_DEFINED
#else
#define yyset_in op_ruleset_in
#endif

#ifdef yyget_out
#define op_ruleget_out_ALREADY_DEFINED
#else
#define yyget_out op_ruleget_out
#endif

#ifdef yyset_out
#define op_ruleset_out_ALREADY_DEFINED
#else
#define yyset_out op_ruleset_out
#endif

#ifdef yyget_leng
#define op_ruleget_leng_ALREADY_DEFINED
#else
#define yyget_leng op_ruleget_leng
#endif

#ifdef yyget_text
#define op_ruleget_text_ALREADY_DEFINED
#else
#define yyget_text op_ruleget_text
#endif

#ifdef yyget_lineno
#define op_ruleget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno op_ruleget_lineno
#endif

#ifdef yyset_lineno
#define op_ruleset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno op_ruleset_lineno
#endif

#ifdef yywrap
#define op_rulewrap_ALREADY_DEFINED
#else
#define yywrap op_rulewrap
#endif

#ifdef yyalloc
#define op_rulealloc_ALREADY_DEFINED
#else
#define yyalloc op_rulealloc
#endif

#ifdef yyrealloc
#define op_rulerealloc_ALREADY_DEFINED
#else
#define yyrealloc op_rulerealloc
#endif

#ifdef yyfree
#define op_rulefree_ALREADY_DEFINED
#else
#define yyfree op_rulefree
#endif

#ifdef yytext
#define op_ruletext_ALREADY_DEFINED
#else
#define yytext op_ruletext
#endif

#ifdef yyleng
#define op_ruleleng_ALREADY_DEFINED
#else
#define yyleng op_ruleleng
#endif

#ifdef yyin
#define op_rulein_ALREADY_DEFINED
#else
#define yyin op_rulein
#endif

#ifdef yyout
#define op_ruleout_ALREADY_DEFINED
#else
#define yyout op_ruleout
#endif

#ifdef yy_flex_debug
#define op_rule_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug op_rule_flex_debug
#endif

#ifdef yylineno
#define op_rulelineno_ALREADY_DEFINED
#else
#define yylineno op_rulelineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 56
#define YY_END_OF_BUFFER 57
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[223] =
    {   0,
        0,    0,   57,   55,   55,   55,    1,    1,   51,   51,
       51,    1,    6,   38,    7,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,    1,   54,   54,   52,    0,   51,    0,   51,   51,
       51,   51,   37,    5,    2,    3,    4,   54,   54,   54,
       54,   54,   54,   54,   54,   50,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   12,   54,   54,   54,   54,
       54,   54,   21,   54,   54,   54,   54,   54,   54,   54,
       54,   25,   54,   54,   54,    0,   53,    0,   51,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    8,   54,

       22,   42,   42,   54,   47,   42,   10,   54,   42,   54,
       54,   54,   42,   42,   42,   54,   11,   54,   42,   54,
       42,   49,   54,   23,   42,   42,   35,   54,   54,   54,
       54,   42,   24,   54,   54,   54,   54,   54,   54,   54,
       54,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   54,   43,   54,   48,   54,   36,   54,   54,
       13,   15,   14,   16,   54,   54,   34,   29,   54,    9,
       54,   30,   28,   19,   26,   54,   45,   40,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       54,   54,   18,   54,   54,   54,   46,   54,   54,   54,

       27,    0,   54,   54,   20,   33,   17,   54,   44,   54,
        0,   54,   54,   32,   19,    0,   54,   43,   39,   54,
       31,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    5,    6,
        6,    6,    7,    6,    8,    9,    6,   10,   11,   12,
       13,   14,   14,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
        6,    1,    6,    6,   21,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
       72,   47,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    1,    2,    2,    1,    1,    2,    1,    3,
        3,    3,    3,    3,    3,    1,    1,    1,    1,    1,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4
    } ;

static const flex_int16_t yy_base[226] =
    {   0,
        0,    0,  249,  584,  229,    0,  584,   63,   70,   81,
       88,  220,   67,  174,  173,   81,    0,   84,   43,   85,
       72,   82,   98,   91,  126,   76,   89,  111,   75,  107,
      131,  129,  130,  134,  584,  170,  189,  198,  206,  250,
      157,  213,  584,  584,  584,  584,  584,    0,  121,  139,
      139,  131,  143,  201,  157,    0,  177,  196,  207,  189,
      217,  214,  210,  215,  217,    0,  251,  243,  219,  232,
      251,  242,    0,  266,  269,  274,  263,  297,  260,  278,
      276,    0,  264,  301,  302,  119,  584,  223,  329,  355,
      309,  303,  307,  314,  313,  301,  323,  322,    0,  307,

        0,    0,    0,  326,    0,    0,    0,  314,    0,  319,
      337,  346,    0,    0,    0,  350,    0,  347,    0,  165,
        0,  167,  340,    0,    0,    0,    0,  358,  360,  349,
      347,    0,    0,  347,  350,  353,  356,  366,  358,  361,
      356,  412,  364,  376,  382,  385,  375,  398,  389,  394,
      397,  402,  406,  400,  416,    0,  403,    0,  422,  403,
        0,    0,    0,    0,  417,  417,    0,    0,  412,    0,
      408,    0,    0,    0,    0,  424,    0,  584,  387,  440,
      466,  469,  472,  475,  478,  481,  484,  487,  490,  493,
      465,  478,    0,  483,  471,  474,    0,  488,  478,  472,

        0,  505,  488,  488,    0,    0,    0,  482,    0,  487,
      515,  509,  506,    0,    0,  531,  510,    0,  584,  526,
        0,  584,  118,  576,  579
    } ;

static const flex_int16_t yy_def[226] =
    {   0,
      222,    1,  222,  222,  222,  223,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  222,  225,  222,  222,  222,  222,
       40,  222,  222,  222,  222,  222,  222,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  225,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  224,  224,

      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,

      224,  222,  224,  224,  224,  224,  224,  224,  224,  224,
      222,  224,  224,  224,  224,  222,  224,  224,  222,  224,
      224,    0,  222,  222,  222
    } ;

static const flex_int16_t yy_nxt[657] =
    {   0,
        4,    5,    4,    4,    6,    7,    7,    7,    8,    9,
        9,    9,   10,   11,   11,   12,    7,   13,   14,   15,
        4,   16,   17,   17,   18,   19,   20,   17,   21,   22,
       23,   17,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   17,   17,   33,   17,   34,   17,   16,   17,   17,
       18,   19,   20,   17,   21,   22,   23,   17,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   17,   17,   33,
       17,   34,   37,   37,   37,   37,   37,   37,   39,   40,
       40,   40,   40,   40,   40,   44,   45,   57,   38,   39,
       41,   41,   41,   41,   41,   41,   39,   42,   42,   42,

       42,   42,   42,   49,   50,   54,   58,   60,   61,   55,
       59,   71,   72,   57,   38,   51,   76,   52,   62,   63,
       65,   36,   53,   87,   56,   66,   67,   73,   77,   49,
       50,   54,   58,   60,   61,   55,   59,   71,   72,   64,
       74,   51,   76,   52,   62,   63,   65,   68,   53,   75,
       56,   66,   67,   73,   77,   69,   78,   81,   84,   85,
       99,   70,  100,  101,   82,   64,   74,   83,   79,  102,
      103,   80,  222,   68,   87,   75,  161,  162,  163,  164,
      106,   69,   78,   81,   84,   85,   99,   70,  100,  101,
       82,   47,   46,   83,   79,  102,  103,   80,   37,   37,

       37,   37,   37,   37,   88,   88,  106,   89,   89,   89,
       89,   89,   89,  107,   38,   37,   37,   37,   37,   37,
       37,   39,   42,   42,   42,   42,   42,   42,  108,  109,
      110,   38,   89,   89,   89,   89,   89,   89,   43,  107,
       38,  104,  111,  112,  113,   35,  105,  114,  222,  115,
      222,  116,  222,  122,  108,  109,  110,   38,   39,   42,
       42,   42,   42,   42,   42,   90,  123,  104,  111,  112,
      113,   91,  105,  114,   92,  115,   93,  116,  117,  122,
       94,  119,  126,   95,   96,   97,  118,  120,  121,   98,
      127,  124,  123,  125,  128,  129,  130,   91,  134,  135,

       92,  137,   93,  136,  117,  138,   94,  119,  126,   95,
       96,   97,  118,  120,  121,   98,  127,  124,  131,  125,
      128,  129,  130,  141,  134,  135,  139,  137,  145,  136,
      140,  138,  146,  132,  149,  147,  150,  133,   89,   89,
       89,   89,   89,   89,  131,  143,  151,  152,  153,  141,
      144,  154,  139,  155,  145,  148,  140,  156,  146,  132,
      149,  147,  150,  133,  142,  142,  142,  142,  142,  157,
      158,  143,  151,  152,  153,  159,  144,  154,  160,  155,
      165,  148,  166,  156,  167,  168,  169,  170,  171,  172,
      173,  174,  175,  176,  177,  157,  158,  202,  202,  202,

      222,  159,  179,  180,  160,  181,  165,  182,  166,  183,
      167,  168,  169,  170,  171,  172,  173,  174,  175,  176,
      177,  178,  178,  178,  178,  178,  178,  186,  179,  180,
      184,  181,  185,  182,  187,  183,  188,  189,  190,  191,
      192,  193,  194,  195,  196,  197,  198,  199,  200,  201,
      202,  202,  202,  186,  222,  222,  184,  222,  185,  222,
      187,  222,  188,  189,  190,  191,  192,  193,  194,  195,
      196,  197,  198,  199,  200,  201,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,

      202,  202,  202,  202,  202,  202,  203,  204,  205,  206,
      207,  208,  209,  210,  211,  211,  211,  211,  211,  211,
      212,  213,  214,  215,  216,  216,  216,  216,  216,  216,
      217,  218,  203,  204,  205,  206,  207,  208,  209,  210,
      219,  219,  219,  219,  219,  219,  212,  213,  214,  215,
      220,  221,  222,  222,  222,  222,  217,  218,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  220,  221,   48,   48,
       86,   86,   86,    3,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222
    } ;

static const flex_int16_t yy_chk[657] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,    8,    8,    8,    8,    8,    9,    9,
        9,    9,    9,    9,    9,   13,   13,   19,    8,   10,
       10,   10,   10,   10,   10,   10,   11,   11,   11,   11,

       11,   11,   11,   16,   16,   18,   20,   21,   22,   18,
       20,   26,   27,   19,    8,   16,   29,   16,   22,   23,
       24,  223,   16,   86,   18,   24,   24,   27,   30,   16,
       16,   18,   20,   21,   22,   18,   20,   26,   27,   23,
       28,   16,   29,   16,   22,   23,   24,   25,   16,   28,
       18,   24,   24,   27,   30,   25,   31,   32,   33,   34,
       49,   25,   50,   51,   32,   23,   28,   32,   31,   52,
       53,   31,   41,   25,   36,   28,  120,  120,  122,  122,
       55,   25,   31,   32,   33,   34,   49,   25,   50,   51,
       32,   15,   14,   32,   31,   52,   53,   31,   37,   37,

       37,   37,   37,   37,   38,   38,   55,   38,   38,   38,
       38,   38,   38,   57,   37,   39,   39,   39,   39,   39,
       39,   42,   42,   42,   42,   42,   42,   42,   58,   59,
       60,   39,   88,   88,   88,   88,   88,   88,   12,   57,
       37,   54,   61,   62,   63,    5,   54,   64,    3,   64,
        0,   65,    0,   69,   58,   59,   60,   39,   40,   40,
       40,   40,   40,   40,   40,   40,   70,   54,   61,   62,
       63,   40,   54,   64,   40,   64,   40,   65,   67,   69,
       40,   68,   72,   40,   40,   40,   67,   68,   68,   40,
       74,   71,   70,   71,   75,   76,   77,   40,   79,   80,

       40,   81,   40,   80,   67,   83,   40,   68,   72,   40,
       40,   40,   67,   68,   68,   40,   74,   71,   78,   71,
       75,   76,   77,   85,   79,   80,   84,   81,   92,   80,
       84,   83,   93,   78,   95,   94,   96,   78,   89,   89,
       89,   89,   89,   89,   78,   91,   97,   98,  100,   85,
       91,  104,   84,  108,   92,   94,   84,  110,   93,   78,
       95,   94,   96,   78,   90,   90,   90,   90,   90,  111,
      112,   91,   97,   98,  100,  116,   91,  104,  118,  108,
      123,   94,  128,  110,  129,  130,  131,  134,  135,  136,
      137,  138,  139,  140,  141,  111,  112,  179,  179,  179,

        0,  116,  143,  144,  118,  145,  123,  146,  128,  147,
      129,  130,  131,  134,  135,  136,  137,  138,  139,  140,
      141,  142,  142,  142,  142,  142,  142,  149,  143,  144,
      148,  145,  148,  146,  149,  147,  150,  151,  152,  153,
      154,  155,  157,  159,  160,  165,  166,  169,  171,  176,
      180,  180,  180,  149,    0,    0,  148,    0,  148,    0,
      149,    0,  150,  151,  152,  153,  154,  155,  157,  159,
      160,  165,  166,  169,  171,  176,  181,  181,  181,  182,
      182,  182,  183,  183,  183,  184,  184,  184,  185,  185,
      185,  186,  186,  186,  187,  187,  187,  188,  188,  188,

      189,  189,  189,  190,  190,  190,  191,  192,  194,  195,
      196,  198,  199,  200,  202,  202,  202,  202,  202,  202,
      203,  204,  208,  210,  211,  211,  211,  211,  211,  211,
      212,  213,  191,  192,  194,  195,  196,  198,  199,  200,
      216,  216,  216,  216,  216,  216,  203,  204,  208,  210,
      217,  220,    0,    0,    0,    0,  212,  213,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  217,  220,  224,  224,
      225,  225,  225,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
/* Lexer specification for operating rules*/
#ifdef _WIN32
// The following pragmas disable stupid warnings in MSVC
#pragma warning (disable:4786)   // identifier truncated to '255' characters
#pragma warning (disable:4065)   // switch contains 'default'
#define _CRTDBG_MAP_ALLOC
#include <stdlib.h>
#include <crtdbg.h>
#else
#define __MIN_PORTABLE(a,b)  ({ __typeof__ (a) _a = (a); __typeof__ (b) _b = (b); _a < _b ? _a : _b; })
#endif
				
#include<iostream>
#include<string>
#include<map>
#include<vector>

#include "oprule/parser/ParseSymbolManagement.h"
#include "op_rule_tab.h"

using namespace std;
using namespace oprule::parser;
using namespace oprule::rule;
using namespace oprule::expression;

#define YY_NO_UNISTD_H
#define YYPARSE op_ruleparse
#define YYLEX op_rulelex
#undef YY_INPUT
#define YY_INPUT(b, r, ms) (r = yaccstring(b, ms))
#define yylval op_rulelval

#define _SETD add_temp_symbol
#define _SETB add_temp_symbol

char *strinput;
char *strinputptr; 
char *inputlim;
map<string,int > monthmap;
double month_to_double(const string& mstr);
int month_to_int(const string& mstr);

int yaccstring(char* buf, int max_size)
{
#ifdef _WIN32
   int n=__min(max_size,inputlim-strinputptr);
#else
   int n=__MIN_PORTABLE(max_size,inputlim-strinputptr);
#endif
   if(n>0){
      memcpy(buf, strinputptr, n);
	  strinputptr += n;
   }
   return n;
}

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{

         /* Puctuation and operators*/

         /* Math operations */ 

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 223 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 222 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{return yytext[0];}
	YY_BREAK
case 2:
YY_RULE_SETUP
{return NE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
{return EQ;}
	YY_BREAK
case 4:
YY_RULE_SETUP
{return GE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
{return LE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
{return LT;  }
	YY_BREAK
case 7:
YY_RULE_SETUP
{return GT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
{return ABS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
{return SQRT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
{return EXP;}
	YY_BREAK
case 11:
YY_RULE_SETUP
{return LOG;}
	YY_BREAK
case 12:
YY_RULE_SETUP
{return LN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
{return MAX2;}
	YY_BREAK
case 14:
YY_RULE_SETUP
{return MIN2;}
	YY_BREAK
case 15:
YY_RULE_SETUP
{return MAX3;}
	YY_BREAK
case 16:
YY_RULE_SETUP
{return MIN3;}
	YY_BREAK
case 17:
YY_RULE_SETUP
{return LOOKUP;}
	YY_BREAK
case 18:
YY_RULE_SETUP
{return FALSE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
{ return TRUE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
{return IFELSE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
{return OR;}   
	YY_BREAK
case 22:
YY_RULE_SETUP
{return AND;}
	YY_BREAK
case 23:
YY_RULE_SETUP
{return NOT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
{ return SET; }
	YY_BREAK
case 25:
YY_RULE_SETUP
{ return TO; }
	YY_BREAK
case 26:
YY_RULE_SETUP
{ return WHEN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
{ return WHILE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
{ return THEN;}
	YY_BREAK
case 29:
YY_RULE_SETUP
{ return RAMP;}
	YY_BREAK
case 30:
YY_RULE_SETUP
{ return STEP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
{return ACCUMULATE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
{return PREDICT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
{return LINEAR; }
	YY_BREAK
case 34:
YY_RULE_SETUP
{return QUAD;   }
	YY_BREAK
case 35:
YY_RULE_SETUP
{return PID;   }
	YY_BREAK
case 36:
YY_RULE_SETUP
{return IPID; }
	YY_BREAK
case 37:
YY_RULE_SETUP
{return ASSIGN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
{return DEFINE; } 
	YY_BREAK
/* Terminal quanitities: named time series, numbers, etc. */
case 39:
YY_RULE_SETUP
{ yylval.stringval=add_to_string_list(yytext);
							   return REFDATE;  }
	YY_BREAK
case 40:
YY_RULE_SETUP
{ yylval.stringval=add_to_string_list(yytext);
							    return REFTIME; }
	YY_BREAK
case 41:
YY_RULE_SETUP
{ yylval.stringval=add_to_string_list(yytext);
                                return REFSEASON; }
	YY_BREAK
case 42:
YY_RULE_SETUP
{                       yylval.dval=month_to_double(yytext); 
                                return NUMBER; }
	YY_BREAK
case 43:
YY_RULE_SETUP
{return DATETIME;}
	YY_BREAK
case 44:
YY_RULE_SETUP
{return SEASON;}
	YY_BREAK
case 45:
YY_RULE_SETUP
{yylval.stringval=add_to_string_list(yytext); return YEAR;}
	YY_BREAK
case 46:
YY_RULE_SETUP
{yylval.stringval=add_to_string_list(yytext); return MONTH;}
	YY_BREAK
case 47:
YY_RULE_SETUP
{yylval.stringval=add_to_string_list(yytext); return DAY;}
	YY_BREAK
case 48:
YY_RULE_SETUP
{yylval.stringval=add_to_string_list(yytext); return HOUR;}
	YY_BREAK
case 49:
YY_RULE_SETUP
{yylval.stringval=add_to_string_list(yytext); return MIN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
{yylval.stringval=add_to_string_list(yytext); return DT;} 
	YY_BREAK
case 51:
YY_RULE_SETUP
{ 
             /* number, possibly with exponent*/
             yylval.dval = atof(yytext); return NUMBER; }  
	YY_BREAK
case 52:
YY_RULE_SETUP
/* ignore whitespace */
	YY_BREAK
case 53:
YY_RULE_SETUP
{
            //cout << "lexing quoted name: " << yytext <<endl;
			string parsetext(yytext);
			size_t beg=parsetext.find_first_not_of(" \"\'");
			size_t end=parsetext.find_last_not_of(" \"\'");
			yylval.stringval=add_to_string_list(string(parsetext,beg, end-beg+1));
            return QUOTEDSTRING;
			}
	YY_BREAK
case 54:
YY_RULE_SETUP
{
            // A generic name, not a reserved word in the oprule language:
			// We will look it up in this order:
			//     1. named oprule expressions
			//     2. model variables and names (including constants, time
			//        series, etc...anything the model provider designates as
			//        a named, retrievable variable.
			//     3. an unknown name -- we give the parser the name as a string
            std::string name(yytext);
			symbol sym=name_lookup(name);
			// First shot: look up names that have been defined
			// earlier in oprule expressions 
			if (sym.type() != symbol::EMPTY ){
			   if (sym.type() == symbol::DOUBLE) { 
			      yylval.pnode=_SETD(sym.dblval); 
				  return NAMEDVAL;}                  
			   else if(sym.type()== symbol::BOOL){
			      yylval.pbnode=_SETB(sym.boolval); return BOOLNAMEDVAL; 
			   }
			 }
			// Second shot: ask the model-provided NamedValueLookup 
			// to interpret the name
            NamedValueLookup & lookup = *get_lookup();

            if ( lookup.isModelName(name) ){
               if (lookup.readWriteType(name)== NamedValueLookup::READWRITE){
                 if(lookup.takesArguments(name)){
				    clear_arg_map();
				    symbol s(name);
				    yylval.stringval=add_temp_symbol(s);
                    return IFPARAM;
                 }else{
                    symbol s(name);
				    yylval.stringval=add_temp_symbol(s);
	                return IFNAME;
                 }
               }else{
			     assert( lookup.readWriteType(name)==NamedValueLookup::READONLY);
                 if(lookup.takesArguments(name)){
				   clear_arg_map();
				   symbol s(name);
                   yylval.stringval=add_temp_symbol(s);
				   return EXPRESSPARAM;
                 }else{
                    symbol s(name);
				    yylval.stringval=add_temp_symbol(s);
	                return EXPRESS;
                 }
			     assert(false);
			     return NAME; // should never get here
               }
			}

			// Last shot: just return the name.
			symbol s(name);
			yylval.stringval=add_temp_symbol(s);
            return NAME;
		}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
{ if (strcmp(yytext," ") != 0) cout << "Unmatched: " << yytext << ";" << endl;}
	YY_BREAK
case 56:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 223 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 223 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 222);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#ifndef yaccinwrap
int op_rulewrap() { return 1; }
#endif

void set_input_string(char* input){
   strinput = input;
   strinputptr = input;
   inputlim=&strinput[strlen(strinput)-1]+1;
}

void set_input_string(string & input){
   set_input_string( const_cast<char*>(input.c_str()) );
}

int op_ruleerror(const char * s){
   cerr << endl << "Error: " << s << "\nin expression  " << strinput << endl;
   cerr << "Error at or before token: '" << yytext << "'"<< endl;
   return 1;
}

void fillmonthmap(){ 
 typedef pair<string,int > strgint;
 monthmap.insert( strgint("JAN",1));
 monthmap.insert( strgint("FEB",2));
 monthmap.insert( strgint("MAR",3));
 monthmap.insert( strgint("APR",4));
 monthmap.insert( strgint("MAY",5));
 monthmap.insert( strgint("JUN",6));
 monthmap.insert( strgint("JUL",7));
 monthmap.insert( strgint("AUG",8));
 monthmap.insert( strgint("SEP",9));
 monthmap.insert( strgint("OCT",10));
 monthmap.insert( strgint("NOV",11));
 monthmap.insert( strgint("DEC",12));
}

double month_to_double(const string& mstr){
   return (double)monthmap[mstr];
}

int month_to_int(const string& mstr){
   return monthmap[mstr];
}

void lexer_init(){
  fillmonthmap();
}

