@echo off
rem This file generated by Jython installer
rem Created on XXX by Administrator
rem
rem set JAVA_HOME=d:\java\sunjdk1.3.0_02\jre



"..\jre\bin\java.exe" "-Dpython.home=d:\vista\Jython" -classpath "d:\vista\Jython\jython.jar;%CLASSPATH%" org.python.util.jython %1 %2 %3 %4 %5 %6 %7 %8 %9

