#ifndef io_file_STORAGE_H__
#define io_file_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>


using namespace std;
using namespace boost;

/** Structure representing input of type io_file.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class io_file
{
public:

  /** Data type io_file, default constructor */  
  typedef const tuple<const std::string,const std::string,const std::string>  identifier_type;

  io_file() :
    
    used(true),
    layer(0)
  {
    fill_n(model,8,'\0');
    fill_n(type,8,'\0');
    fill_n(io,8,'\0');
    fill_n(interval,16,'\0');
    fill_n(file,128,'\0');
  };

  /** Construct a io_file with actual data values */
  io_file(const  char a_model[8],const  char a_type[8],const  char a_io[8],const  char a_interval[16],const  char a_file[128], bool a_used=true, int a_layer = 0) :
    
    used(a_used),
    layer(a_layer)
  {
    memcpy(model,a_model,8);
    memcpy(type,a_type,8);
    memcpy(io,a_io,8);
    memcpy(interval,a_interval,16);
    memcpy(file,a_file,128);  
  }
  
  /**Copy constructor) 
   */
  io_file (const io_file & other) :
    
    used(other.used),
    layer(other.layer)
  {
    memcpy(model,other.model,8);
    memcpy(type,other.type,8);
    memcpy(io,other.io,8);
    memcpy(interval,other.interval,16);
    memcpy(file,other.file,128);  
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( model,type,io );
  }
  
  void set_identifier(identifier_type identifier)
  {
     memcpy(model,identifier.get<0>().c_str(),8);
      memcpy(type,identifier.get<1>().c_str(),8);
      memcpy(io,identifier.get<2>().c_str(),8);
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  io_file::identifier_type parent_identifier()  const
  {
     return io_file::identifier_type( model,type,io );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<io_file>& pbuf = HDFTableManager<io_file>::instance().buffer();
    io_file parent;
    parent.set_identifier(parent_identifier());
    vector<io_file>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<io_file>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const io_file & other) const
  {
     
     if(this->identifier() != other.identifier())
	 {
		 return this->identifier() < other.identifier();
	 }
	 // todo: make this a policy
	 bool layerOutranks = (this->layer == 0 && other.layer != 0) ||
		                  (this->layer > other.layer && other.layer != 0);
     return layerOutranks;

  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const io_file & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  io_file& operator=(const io_file& rhs)
  {
    strcpy(this->model,rhs.model);
    strcpy(this->type,rhs.type);
    strcpy(this->io,rhs.io);
    strcpy(this->interval,rhs.interval);
    strcpy(this->file,rhs.file);
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (io_file) */
  string objectName() const
  { 
    return "io_file"; 
  }

  
  char model[8];
  char type[8];
  char io[8];
  char interval[16];
  char file[128];
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<io_file> io_file_table;

hid_t string_type(size_t n);

TableDescription io_file_table_description();

istream& operator>> (istream& stream, io_file & obj);
ostream& operator<<(ostream & stream, const io_file & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void io_file_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int io_file_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void io_file_append_to_buffer_f(const  char a_model[8],const  char a_type[8],const  char a_io[8],const  char a_interval[16],const  char a_file[128], int * ierror, 
              const int model_len,const int type_len,const int io_len,const int interval_len,const int file_len);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void io_file_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void io_file_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void io_file_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void io_file_query_from_buffer_f(size_t* row, 
                         char a_model[8], char a_type[8], char a_io[8], char a_interval[16], char a_file[128], int * ierror, 
              int model_len,int type_len,int io_len,int interval_len,int file_len);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void io_file_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void io_file_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

