#ifndef operating_rule_STORAGE_H__
#define operating_rule_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>


using namespace std;
using namespace boost;

/** Structure representing input of type operating_rule.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class operating_rule
{
public:

  /** Data type operating_rule, default constructor */  
  typedef const tuple<const std::string>  identifier_type;

  operating_rule() :
    
    used(true),
    layer(0)
  {
    fill_n(name,32,'\0');
    fill_n(action,512,'\0');
    fill_n(trigger,512,'\0');
  };

  /** Construct a operating_rule with actual data values */
  operating_rule(const  char a_name[32],const  char a_action[512],const  char a_trigger[512], bool a_used=true, int a_layer = 0) :
    
    used(a_used),
    layer(a_layer)
  {
    memcpy(name,a_name,32);
    memcpy(action,a_action,512);
    memcpy(trigger,a_trigger,512);  
  }
  
  /**Copy constructor) 
   */
  operating_rule (const operating_rule & other) :
    
    used(other.used),
    layer(other.layer)
  {
    memcpy(name,other.name,32);
    memcpy(action,other.action,512);
    memcpy(trigger,other.trigger,512);  
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( name );
  }
  
  void set_identifier(identifier_type identifier)
  {
     memcpy(name,identifier.get<0>().c_str(),32);
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  operating_rule::identifier_type parent_identifier()  const
  {
     return operating_rule::identifier_type( name );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<operating_rule>& pbuf = HDFTableManager<operating_rule>::instance().buffer();
    operating_rule parent;
    parent.set_identifier(parent_identifier());
    vector<operating_rule>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<operating_rule>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const operating_rule & other) const
  {
     
     if(this->identifier() != other.identifier())
	 {
		 return this->identifier() < other.identifier();
	 }
	 // todo: make this a policy
	 bool layerOutranks = (this->layer == 0 && other.layer != 0) ||
		                  (this->layer > other.layer && other.layer != 0);
     return layerOutranks;

  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const operating_rule & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  operating_rule& operator=(const operating_rule& rhs)
  {
    strcpy(this->name,rhs.name);
    strcpy(this->action,rhs.action);
    strcpy(this->trigger,rhs.trigger);
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (operating_rule) */
  string objectName() const
  { 
    return "operating_rule"; 
  }

  
  char name[32];
  char action[512];
  char trigger[512];
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<operating_rule> operating_rule_table;

hid_t string_type(size_t n);

TableDescription operating_rule_table_description();

istream& operator>> (istream& stream, operating_rule & obj);
ostream& operator<<(ostream & stream, const operating_rule & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void operating_rule_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int operating_rule_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void operating_rule_append_to_buffer_f(const  char a_name[32],const  char a_action[512],const  char a_trigger[512], int * ierror, 
              const int name_len,const int action_len,const int trigger_len);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void operating_rule_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void operating_rule_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void operating_rule_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void operating_rule_query_from_buffer_f(size_t* row, 
                         char a_name[32], char a_action[512], char a_trigger[512], int * ierror, 
              int name_len,int action_len,int trigger_len);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void operating_rule_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void operating_rule_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

