#ifndef particle_insertion_STORAGE_H__
#define particle_insertion_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>


using namespace std;
using namespace boost;

/** Structure representing input of type particle_insertion.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class particle_insertion
{
public:

  /** Data type particle_insertion, default constructor */  
  typedef const tuple<const int&,const std::string>  identifier_type;

  particle_insertion() :
    node(-901),
    nparts(-901),
    used(true),
    layer(0)
  {
    fill_n(delay,8,'\0');
    fill_n(duration,16,'\0');
  };

  /** Construct a particle_insertion with actual data values */
  particle_insertion(const int & a_node,const int & a_nparts,const  char a_delay[8],const  char a_duration[16], bool a_used=true, int a_layer = 0) :
    node(a_node),
    nparts(a_nparts),
    used(a_used),
    layer(a_layer)
  {
    memcpy(delay,a_delay,8);
    memcpy(duration,a_duration,16);  
  }
  
  /**Copy constructor) 
   */
  particle_insertion (const particle_insertion & other) :
    node(other.node),
    nparts(other.nparts),
    used(other.used),
    layer(other.layer)
  {
    memcpy(delay,other.delay,8);
    memcpy(duration,other.duration,16);  
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( node,delay );
  }
  
  void set_identifier(identifier_type identifier)
  {
     node=identifier.get<0>();
      memcpy(delay,identifier.get<1>().c_str(),8);
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  particle_insertion::identifier_type parent_identifier()  const
  {
     return particle_insertion::identifier_type( node,delay );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<particle_insertion>& pbuf = HDFTableManager<particle_insertion>::instance().buffer();
    particle_insertion parent;
    parent.set_identifier(parent_identifier());
    vector<particle_insertion>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<particle_insertion>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const particle_insertion & other) const
  {
     
     if(this->identifier() != other.identifier())
	 {
		 return this->identifier() < other.identifier();
	 }
	 // todo: make this a policy
	 bool layerOutranks = (this->layer == 0 && other.layer != 0) ||
		                  (this->layer > other.layer && other.layer != 0);
     return layerOutranks;

  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const particle_insertion & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  particle_insertion& operator=(const particle_insertion& rhs)
  {
    this->node=rhs.node;
    this->nparts=rhs.nparts;
    strcpy(this->delay,rhs.delay);
    strcpy(this->duration,rhs.duration);
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (particle_insertion) */
  string objectName() const
  { 
    return "particle_insertion"; 
  }

  
  int node;
  int nparts;
  char delay[8];
  char duration[16];
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<particle_insertion> particle_insertion_table;

hid_t string_type(size_t n);

TableDescription particle_insertion_table_description();

istream& operator>> (istream& stream, particle_insertion & obj);
ostream& operator<<(ostream & stream, const particle_insertion & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void particle_insertion_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int particle_insertion_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void particle_insertion_append_to_buffer_f(const int * a_node,const int * a_nparts,const  char a_delay[8],const  char a_duration[16], int * ierror, 
              const int delay_len,const int duration_len);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void particle_insertion_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void particle_insertion_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void particle_insertion_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void particle_insertion_query_from_buffer_f(size_t* row, 
                        int * a_node,int * a_nparts, char a_delay[8], char a_duration[16], int * ierror, 
              int delay_len,int duration_len);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void particle_insertion_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void particle_insertion_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

