#ifndef tidefile_STORAGE_H__
#define tidefile_STORAGE_H__
/**
WARNING: THIS FILE WAS AUTOMATICALLY GENERATED USING A SCRIPT AND A TEMPLATE  
DO NOT CHANGE THE CODE HERE. 
IF THE CODE IS INCORRECT, FIX THE TEMPLATE OR SCRIPT
IF YOU WANT TO ADD NEW ITEMS, ADD THEM TO THE SCRIPT INPUT FILE AND RUN IT AFRESH
*/ 
#define _CRT_SECURE_NO_DEPRECATE  // viz studio deprecation warnings
#include "hdf5.h"
#include "hdf5_hl.h"
#include "hdf_storage.h"
#include "HDFTableManager.h"
#include "TableDescription.h"
#include "TableItemFunctors.h"
#include "boost/tuple/tuple_comparison.hpp"
#include "boost/tuple/tuple_io.hpp"
#include<iostream>
#include<vector>
#include<algorithm>
#include<string.h>
#include<iostream>


using namespace std;
using namespace boost;

/** Structure representing input of type tidefile.
    This class is autogenerated by a script given
    a description of the object
    \ingroup userdata
*/
class tidefile
{
public:

  /** Data type tidefile, default constructor */  
  typedef const tuple<const std::string>  identifier_type;

  tidefile() :
    
    used(true),
    layer(0)
  {
    fill_n(start_date,16,'\0');
    fill_n(end_date,16,'\0');
    fill_n(file,128,'\0');
  };

  /** Construct a tidefile with actual data values */
  tidefile(const  char a_start_date[16],const  char a_end_date[16],const  char a_file[128], bool a_used=true, int a_layer = 0) :
    
    used(a_used),
    layer(a_layer)
  {
    memcpy(start_date,a_start_date,16);
    memcpy(end_date,a_end_date,16);
    memcpy(file,a_file,128);  
  }
  
  /**Copy constructor) 
   */
  tidefile (const tidefile & other) :
    
    used(other.used),
    layer(other.layer)
  {
    memcpy(start_date,other.start_date,16);
    memcpy(end_date,other.end_date,16);
    memcpy(file,other.file,128);  
  }
  
  /** Identifier that distinguishes whether two entries are distinct */
  identifier_type identifier()  const
  {  
     return identifier_type( start_date );
  }
  
  void set_identifier(identifier_type identifier)
  {
     memcpy(start_date,identifier.get<0>().c_str(),16);
  }
  
  /** Parent object class name.
      If this is a child item belonging to a parent, returns
      the name of the parent class. Otherwise returns the name
      of this class.
  */
  tidefile::identifier_type parent_identifier()  const
  {
     return tidefile::identifier_type( start_date );
  }

  /** Return the version/layer number of the parent object */ 
  int parent_version()  const
  {
    vector<tidefile>& pbuf = HDFTableManager<tidefile>::instance().buffer();
    tidefile parent;
    parent.set_identifier(parent_identifier());
    vector<tidefile>::iterator loc = lower_bound(pbuf.begin(),
                                                pbuf.end(),
                                                parent,
                                                identifier_compare<tidefile>());
    bool found = (loc!=pbuf.end()) && loc->identifier() == parent.identifier();    
    if (found && loc->used){ return loc->layer; }
    else{ return -1; }
  }

  /** Return true if this layer of this object matches the layer of the parent object that will be use in the model.*/
  bool parent_valid()  const
  {
    return this->layer == parent_version();
  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator< (const tidefile & other) const
  {
     
     if(this->identifier() != other.identifier())
	 {
		 return this->identifier() < other.identifier();
	 }
	 // todo: make this a policy
	 bool layerOutranks = (this->layer == 0 && other.layer != 0) ||
		                  (this->layer > other.layer && other.layer != 0);
     return layerOutranks;

  }

  /** Less-than operator based on the identifier plus (for parent objects) layer number*/  
  bool operator== (const tidefile & other) const
  {
     return ((*this < other ) || (other < *this)) ? false : true;
  }
  
  /** Assignment that includes all the data plus the used and layer fields */
  tidefile& operator=(const tidefile& rhs)
  {
    strcpy(this->start_date,rhs.start_date);
    strcpy(this->end_date,rhs.end_date);
    strcpy(this->file,rhs.file);
    used = rhs.used;
    layer = rhs.layer;
    return *this;
  }

  /** Return the class name of this object (tidefile) */
  string objectName() const
  { 
    return "tidefile"; 
  }

  
  char start_date[16];
  char end_date[16];
  char file[128];
  /** indicator that the entry is used (true if not marked deleted by user)*/
  bool used;  
  /** layer (version number) of this entry */
  int layer;
};

typedef HDFTableManager<tidefile> tidefile_table;

hid_t string_type(size_t n);

TableDescription tidefile_table_description();

istream& operator>> (istream& stream, tidefile & obj);
ostream& operator<<(ostream & stream, const tidefile & obj);



////////// FORTRAN-LINKABLE API //////////
#define FCALL extern "C"


/**
  Clear the buffer, compatible with fortran
*/  
FCALL void tidefile_clear_buffer_f();

/** query number of records being stored in buffer */
FCALL int tidefile_buffer_size_f();


/** append to buffer, compatible with fortran, returns new size*/
FCALL void tidefile_append_to_buffer_f(const  char a_start_date[16],const  char a_end_date[16],const  char a_file[128], int * ierror, 
              const int start_date_len,const int end_date_len,const int file_len);
  
/** both makes the table and writes the contents of the buffer to it */
FCALL void tidefile_write_buffer_to_hdf5_f(const hid_t* file_id, int* ierror);

/** reads the table in from a file into the buffer*/
FCALL void tidefile_read_buffer_from_hdf5_f(const hid_t* file_id, int* ierror);

/** query size information about the table in hdf5
*/
FCALL void tidefile_number_rows_hdf5_f(const hid_t* file_id, hsize_t* nrecords, int* ierror);


/** get one row worth of information from the buffer */
FCALL void tidefile_query_from_buffer_f(size_t* row, 
                         char a_start_date[16], char a_end_date[16], char a_file[128], int * ierror, 
              int start_date_len,int end_date_len,int file_len);
/**
  prioritize buffer by layers, delete unused items and sort
  */
FCALL void tidefile_prioritize_buffer_f(int* ierror);
/**
   write buffer to the given text file. File will be appended if exists and append flag is set to true.
   otherwise the file will be created or overwritten.
 */
FCALL void tidefile_write_buffer_to_text_f(const char* file, const bool* append, int* ierror, int filelen);


#endif

